from pathlib import Path
p=Path('/home/ubuntu/thai-order-project-vault/client/src/pages/ChatHub.tsx')
s=p.read_text()
old='</div> : <p className="mt-5 rounded-2xl border border-violet-500/10 bg-black/20 p-4 text-sm text-violet-100/50">ยังไม่พบออเดอร์ที่เชื่อมกับห้องนี้</p>}</div></div> : null}'
new='</div> : <p className="mt-5 rounded-2xl border border-violet-500/10 bg-black/20 p-4 text-sm text-violet-100/50">ยังไม่พบออเดอร์ที่เชื่อมกับห้องนี้</p>}{chatEvidenceQuery.isLoading ? <div className="mt-5 flex items-center gap-2 text-xs text-cyan-200/70"><LoaderCircle className="h-3.5 w-3.5 animate-spin" />กำลังโหลดหลักฐานแชท…</div> : <div className="mt-5 rounded-2xl border border-cyan-400/15 bg-cyan-400/[0.04] p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-200">CHAT EVIDENCE</p><span className="text-[10px] text-cyan-100/50">{chatEvidenceQuery.data?.length ?? 0} รายการ</span></div><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{chatEvidenceQuery.data?.length ? chatEvidenceQuery.data.map(row => <div key={String(row.id)} className="rounded-xl border border-cyan-400/10 bg-black/20 p-2.5"><div className="flex justify-between gap-2 text-[10px] text-cyan-100/45"><span>{String(row.customer_name ?? row.sender_name ?? "ลูกค้า")}</span><span>{timeLabel(String(row.occurred_at ?? row.source_created_at ?? ""))}</span></div><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-violet-50/80">{String(row.message_text ?? "[ข้อความไม่มีตัวอักษร / มีไฟล์แนบ]")}</p><p className="mt-1 truncate text-[9px] text-cyan-100/30">source: {String(row.source_message_id ?? row.dedupe_key ?? "—")}</p></div>) : <p className="text-xs text-cyan-100/45">ยังไม่มีหลักฐานในตาราง chat_customer_evidence หลังต่อ n8n แล้วข้อมูลจะแสดงที่นี่อัตโนมัติ</p>}</div></div>}</div></div> : null}'
if old not in s:
    raise SystemExit('marker not found')
p.write_text(s.replace(old,new,1))
print('inserted')
